### ISSUE TITLE
GeForce GTX 750 Ti 2Gb :  CUDA error 'an illegal memory access was encountered'... (version v0.5c) 

### ISSUE THREAD

**Issue by snowwcone** [kozyilmaz/nheqminer-macos#17] opened 2017-11-26 05:41 UTC
It looks like mining with my processor only works fine however whenever trying to use my gpu i receive this error below. Please keep in mind I don't know very much at all when it comes to coding(?)

C:\Users\braed\Desktop\Windows_x64_nheqminer-5c>nheqminer.exe  -l us-east.zec.slushpool.com:4444 -u [redacted] -cd 0

        ==================== www.nicehash.com ====================
                Equihash CPU&GPU Miner for NiceHash v0.5c
        Thanks to Zcash developers for providing base of the code.
            Special thanks to tromp, xenoncat and djeZo for providing
              optimized CPU and CUDA equihash solvers.
        ==================== www.nicehash.com ====================

Setting log level to 2
[00:23:41][0x00003ad0] Using SSE2: YES
[00:23:41][0x00003ad0] Using AVX: YES
[00:23:41][0x00003ad0] Using AVX2: NO
[00:23:42][0x000022e4] stratum | Starting miner
[00:23:42][0x000022e4] stratum | Connecting to stratum server us-east.zec.slushpool.com:4444
[00:23:42][0x000022f8] miner#0 | Starting thread #0 (CUDA-DJEZO) GeForce GTX 750 Ti (#0) M=2
[00:23:42][0x000022e4] stratum | Connected!
[00:23:42][0x000022e4] stratum | Subscribed to stratum server
[00:23:42][0x000022e4] miner | Extranonce is 2f736c7573682f02680500031c12
[00:23:42][0x000022e4] stratum | Target set to 03ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
[00:23:42][0x000022e4] stratum | Received new job #333d1
[00:23:42][0x000022e4] stratum | Authorized worker [redacted]
[00:23:43][0x000022f8] miner#0 | CUDA error 'an illegal memory access was encountered' in func 'eq_cuda_context<RB, SM, SSM, THREADS, PACKER>::solve' line 2095

C:\Users\braed\Desktop\Windows_x64_nheqminer-5c>CUDA error 'an illegal memory access was encountered'

**Comment by kozyilmaz** [comment] 2017-11-26 10:46
@snowwcone As locmer and Bigsy pointed out in another issue https://github.com/kozyilmaz/nheqminer-macos/issues/13 there is a problem with GM107 based GPU's  (GTX745,750,750TI). I am looking for one however did not find yet.

**Comment by snowwcone** [comment] 2017-11-26 20:40
@kozyilmaz thanks for ppointing that out to me. Is there any recommended miners that are compatible?

**Comment by ziorufus** [comment] 2017-11-27 10:40
Same error for me. I tried to recompile the program with `-DUSE_CUDA_TROMP=ON` in `neqminer/Makefile` (see [here](https://github.com/nicehash/nheqminer/issues/223)) and run it with `-cv 1`. It seems to work, but I get no speed (`Speed [15 sec]: 0 I/s, 0 Sols/s`).
Any idea is appreciated.

**Comment by kozyilmaz** [comment] 2017-11-27 11:14
@snowwcone I believe Claymore has a ZEC Windows miner, not sure if EWBF works on Windows.

**Comment by kozyilmaz** [comment] 2017-11-27 11:20
@ziorufus one of my older releases `nheqminer-old` have CUDA_TROMP. Can you try mining with that? https://github.com/kozyilmaz/nheqminer-macos/releases/tag/v4

**Comment by ziorufus** [comment] 2017-11-27 12:07
I had to disable it, due to a compilation error :(
See #18

**Comment by ziorufus** [comment] 2017-11-27 12:36
As you suggested, I tried v4, but I encountered the same problem: it gives me the error or 0 Sols/s depending on the activation of `CUDA_TROMP`.

**Comment by ziorufus** [comment] 2017-11-27 12:46
If I use `nheqminer-old` it seems to work, but it's really slow :(

```
[13:44:13][0x00007fffe6b0e3c0] Speed [15 sec]: 5.73333 I/s, 10.9333 Sols/s
```
Based on the tables I found on the web, it should go around 40/50 Sols/s.
Using my other GPU (GeForce GTX 1060) I got (on `nheqminer-gpu`)

```
[13:44:26][0x00007fffe6b0e3c0] Speed [15 sec]: 122.533 I/s, 234.533 Sols/s
```

**Comment by ziorufus** [comment] 2017-11-27 12:52
I think that the problem can be solved by making `CUDA_TROMP` working on the newer `nheqminer-gpu`, but honestly I do not know how to do it.

**Comment by ziorufus** [comment] 2017-11-27 13:47
It works! From the information on the mining pool, it seems that the speed is correctly 44 H/s.
I hope this is correct.

Anyway, I made a small donation for the project, @kozyilmaz you deserve it!

**Comment by kozyilmaz** [comment] 2017-11-27 14:14
@ziorufus Thanks, glad that it worked!

**Comment by snowwcone** [comment] 2017-11-27 20:08
@ziorufus did you use the older version of nheqminer? or enabling CUDA_TROMP on the new version?

**Comment by ziorufus** [comment] 2017-11-27 22:48
@snowwcone I used the old version, as the new one gives 0 Sol/s even with `CUDA_TROMP` set to ON.

**Comment by kozyilmaz** [comment] 2018-01-03 21:28
duplicate of https://github.com/kozyilmaz/nheqminer-macos/issues/13, there is an issue with GM107 based GPU's (GTX745,750,750TI)

**Closed by kozyilmaz** 2018-01-03 21:28 UTC
